// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxR2luHNLL90z5aT_WDshUpSyZDto2fBA',
    appId: '1:107461356026:web:4ace0ea8255e976c27dc43',
    messagingSenderId: '107461356026',
    projectId: 'ticohub-ccdd4',
    authDomain: 'ticohub-ccdd4.firebaseapp.com',
    storageBucket: 'ticohub-ccdd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuke4NtwMnCrMd-2i-FDKrypN_doYRWc',
    appId: '1:107461356026:android:8c97b22c9631a8d427dc43',
    messagingSenderId: '107461356026',
    projectId: 'ticohub-ccdd4',
    storageBucket: 'ticohub-ccdd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpy-KhA0cVIS_KmT3jxiyMDdMWSV53v8s',
    appId: '1:107461356026:ios:2a7c827c2a0affad27dc43',
    messagingSenderId: '107461356026',
    projectId: 'ticohub-ccdd4',
    storageBucket: 'ticohub-ccdd4.appspot.com',
    iosClientId:
        '107461356026-lgr4ojd1fhquult8vu283l40m6j7gqkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecook',
  );
}
